apiVersion: carto.run/v1alpha1
kind: Deliverable
metadata:
  labels:
    app.kubernetes.io/component: deliverable
    app.kubernetes.io/part-of: wednesday-java-web-app
    app.tanzu.vmware.com/deliverable-type: web
    apps.tanzu.vmware.com/auto-configure-actuators: "true"
    apps.tanzu.vmware.com/has-tests: "true"
    apps.tanzu.vmware.com/workload-type: web
    carto.run/cluster-template-name: deliverable-template
    carto.run/resource-name: deliverable
    carto.run/supply-chain-name: source-test-scan-to-url
    carto.run/template-kind: ClusterTemplate
    carto.run/template-lifecycle: mutable
    carto.run/workload-name: wednesday-java-web-app
    carto.run/workload-namespace: jeremy
  name: wednesday-java-web-app
  namespace: jeremy
spec:
  source:
    git:
      url: https://github.com/x95castle1/workload-config-repo
      ref:
        branch: main
    subPath: config/jeremy/wednesday-java-web-app