apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: header-app
  labels:
    apps.tanzu.vmware.com/workload-type: server
    apps.tanzu.vmware.com/auto-configure-actuators: "true"
    app.kubernetes.io/part-of: header-app
    apps.tanzu.vmware.com/has-tests: true
  namespace: dev
spec:
  build:
    env:
      - name: BP_JVM_VERSION
        value: "8"
  params:
  - name: annotations
    value:
      autoscaling.knative.dev/minScale: "1"
  source:
    git:
      url: https://github.com/nkalra0123/spring-boot-dump-headers
      ref:
        branch: master